#ifndef CT_SHADERINTEROP_MATRICES_H
#define CT_SHADERINTEROP_MATRICES_H

#include "Common_ShaderInterop.h"

CTSI_NAMESPACE_BEGIN

CTSI_CONSTANT_BUFFER(Matrices, CTSI_CBSLOT_MATRICES)
{
    CTSI_TYPE_MATRIX transform;

    CTSI_TYPE_FLOAT3 cameraLocalPos;
};

CTSI_NAMESPACE_END

#endif // CT_SHADERINTEROP_MATRICES_H