#pragma once

#include "CitromMemory.h"
#define CTL_MEMORY_REALLOCATE(PTR, NEWSIZE) Citrom::Memory::Reallocate(PTR, NEWSIZE)
#define CTL_MEMORY_COPY(DESTINATION, SOURCE, BYTESTOCOPY) Citrom::Memory::Copy(DESTINATION, SOURCE, BYTESTOCOPY)
#define CTL_MEMORY_ALLOCATE_ADD_MEMORY(PTR, CURRENTSIZE, SIZETOADD) Citrom::Memory::AllocateAddMemory(PTR, CURRENTSIZE, SIZETOADD)
#define CTL_MEMORY_SET(PTR, VALUEFOREACHBYTE, BYTESTOSET) Citrom::Memory::Set(PTR, VALUEFOREACHBYTE, BYTESTOSET)
#define CTL_MEMORY_ZERO(PTR, MEMORYBLOCKSIZE) Citrom::Memory::Zero(PTR, MEMORYBLOCKSIZE)

#include "Profiling/Profiler.h" // Citrom Tech Profiler
//#include <typeinfo>
//#define CTL_PROFILE_MEMBER_FUNC() CT_PROFILE_MEMBER_FUNCTION()