#pragma once

#include "CitromMemory.h"
#define CTL_MEMORY_REALLOCATE(PTR, NEWSIZE) Citrom::Memory::Reallocate(PTR, NEWSIZE)
#define CTL_MEMORY_COPY(DESTINATION, SOURCE, BYTESTOCOPY) Citrom::Memory::Copy(DESTINATION, SOURCE, BYTESTOCOPY)
#define CTL_MEMORY_ALLOCATE_ADD_MEMORY(PTR, CURRENTSIZE, SIZETOADD) Citrom::Memory::AllocateAddMemory(PTR, CURRENTSIZE, SIZETOADD)
