#ifndef CT_SHADERINTEROP_COMMON_H
#define CT_SHADERINTEROP_COMMON_H

#include "Core_ShaderInterop.h"

#define CTSI_CBSLOT_MATRICES 0
#define CTSI_CBSLOT_LIGHTING 1
#define CTSI_CBSLOT_MATERIAL 2

#endif // CT_SHADERINTEROP_COMMON_H